<?php 
	session_start();
	$username = "login42007";
	$password = "Lamborghini97!";
	$hostname = "68.178.217.44";

	$dbhandle = mysql_connect($hostname, $username, $password) or die("Could not connect to databasae");

	$selected = mysql_select_db("login42007", $dbhandle);

	$myusername = $_POST['user'];	// sets local php var $myusername = whatever the user put for their username
	$mypassword = $_POST['pass'];	// sets local php var $mypassword = whatever the user put for their password
	
	$_SESSION['name'] = "";													// declares session var name
	$query_name = "SELECT Name FROM Users WHERE Username='$myusername'";	// selects everything in the name row where the Username is $myusername from the User table
	$myname = mysql_query($query_name);										// completes the query
	if($row = mysql_fetch_array($myname,MYSQL_BOTH)) {						// sets $row = the array generated by the query. (which returns true) so if(true)
  		$myname = $row['Name'];												// $myname = element in row array with key "Name"
  		$_SESSION['name'] = $myname;										// sets session var name = $myname
	}
	
	$myusername = stripslashes($myusername);
	$mypassword = stripslashes($mypassword);

	$user_query = "SELECT * FROM Users WHERE Username='$myusername' and Password='$mypassword' "; 		// searches database for given username & password
	$user_result = mysql_query($user_query); 															// sets the result equal to new var $result
	$user_count = mysql_num_rows($user_result);															// counts the number of rows in the result and sets it = to $count

	$admin_query = "SELECT * FROM Admin WHERE admin_name='$myusername' and admin_pass='$mypassword' "; 	// searches database for given username & password
	$admin_result = mysql_query($admin_query); 															// sets the result equal to new var $result
	$admin_count = mysql_num_rows($admin_result);														// counts the number of rows in the result and sets it = to $count


	mysql_close();

	if($user_count > 0 && $admin_count == 0) {					// if there is 1 match between input and database
		session_start();
		$seconds = 120 + time();								// sets variable $seconds to current time + 120 seconds
		setcookie(loggedin, date("F js - g:i a"), $seconds);	// creates a cookie called loggedin which lasts for 120 seconds (clientside)
		$_SESSION['logged_in'] = "YES";							// creates a session cookie (serverside)
		
		$page = $_GET['page'];
		if($page == 'media') {header("location:hcyaMedia.php");}
		else if($page == 'resources') {header("location:hcyaResources.php");}
		else if($page == 'index') {header("location:index.php");}
		else {
			header("location:index.php");						// redirects you to page: login_success.php
		}
	}

	else if($admin_count > 0 && $user_count == 0) {									// if there is 1 match between input and database
		session_start();
		$seconds = 120 + time();													// sets variable $seconds to current time + 120 seconds
		setcookie(loggedin, date("F js - g:i a"), $seconds);						// creates a cookie called loggedin which lasts for 120 seconds (clientside)
		$_SESSION['admin_logged_in'] = "YES";										// creates a session cookie (serverside)
		
		$page = $_GET['page'];
		if($page == 'media') {header("location:hcyaMedia.php");}
		else if($page == 'resources') {header("location:hcyaResources.php");}
		else if($page == 'index') {header("location:index.php");}
		else {
			header("location:admin_view.php");										// redirects you to page: login_success.php
		}
	}

	else if($admin_count > 0 && $user_count > 0) {									// if there is 1 match between input and database
		session_start();
		$seconds = 120 + time();													// sets variable $seconds to current time + 120 seconds
		setcookie(loggedin, date("F js - g:i a"), $seconds);						// creates a cookie called loggedin which lasts for 120 seconds (clientside)
		$_SESSION['admin_logged_in'] = "YES";										// creates a session cookie (serverside)
		
		$page = $_GET['page'];
		if($page == 'media') {header("location:hcyaMedia.php");}
		else if($page == 'resources') {header("location:hcyaResources.php");}
		else if($page == 'index') {header("location:index.php");}
		else {
			header("location:admin_view.php");										// redirects you to page: login_success.php
		}
	}

	else {
		$url = 'hcyaLogin.php';
		$url = strtok($url, '?');
		header("location: hcyaLogin.php?problem=invalidUser");						// if no match is found echos: incorrect username or password
	}
?>